// <auto-generated />
using Competition.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Competition.Migrations
{
    [DbContext(typeof(CompetitionDbContext))]
    [Migration("20260413141145_SeedInstitution")]
    partial class SeedInstitution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Competition.Models.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Звягель",
                            Name = "ДЮКФП міста Звягеля"
                        },
                        new
                        {
                            Id = 2,
                            City = "Олевськ",
                            Name = "Олевська дитячо-юнацька спортивна школа"
                        },
                        new
                        {
                            Id = 3,
                            City = "Баранівка",
                            Name = "Баранівська районна дитячо-юнацька спортивна школа"
                        },
                        new
                        {
                            Id = 4,
                            City = "Андрушівка",
                            Name = "Андрушівська ДЮСШ"
                        },
                        new
                        {
                            Id = 5,
                            City = "Бердичів",
                            Name = "Бердичівська дитячо-юнацька спортивна школа ім. В.О. Лонського"
                        },
                        new
                        {
                            Id = 6,
                            City = "Житомир",
                            Name = "Дитячо-юнацька спортивна школа ЖМР"
                        });
                });

            modelBuilder.Entity("Competition.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BenchPress")
                        .HasColumnType("real");

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Deadlift")
                        .HasColumnType("real");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Squat")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Competition.Models.Participant", b =>
                {
                    b.HasOne("Competition.Models.Institution", "Institution")
                        .WithMany("Participants")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Competition.Models.Institution", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
